### ISSUE TITLE
Libs not found

### ISSUE THREAD

**Issue by guilhermehas** [reinterpretcat/lfs#17]
I got this message in the first command
```
libgmp.la: not found
libmpfr.la: not found
libmpc.la: not found
```

**Comment by fishcharlie** [comment]
@guilhermehas In the first command? Do you mean after running `docker rm lfs`? Those logs are not very detailed at all. Can you provide more information?

**Comment by guilhermehas** [comment]
```
/mnt/lfs/sources /mnt/lfs/sources
Assume toolchain from host is already placed in sources folder
/mnt/lfs/sources
Building binutils..
Approximate build time: 1 SBU
Required disk space: 547 MB
tar: binutils-*.tar.xz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
```
I can not reproduce this error anymore, but I am having this problem at master commit.
At commit of v8.1.0, everything works right.

**Comment by fishcharlie** [comment]
@guilhermehas Great. So you are good to go now? This issue is pretty easy to fix and the error message is super obvious. It can't find `binutils-*.tar.xz`. So gotta make sure it's included in the toolchain folder. I found that sometimes the extension is a bit off and you have to modify the script files to have the extensions match.

Also as mentioned in #15, some issues I had were caused by the LFS wget list giving us links that responded with 404 error messages. In those cases, you need to download the package manually and handle it from there. The solution to fix that long term is probably to upgrade to the latest LFS version. Which I don't think will be happening on this repo anytime soon.

**Comment by fishcharlie** [comment]
@reinterpretcat I think this issue can be closed since the OP has not replied for a significant period of time.
