### ISSUE TITLE
Why is 8.4-setup-grub skipped?

### ISSUE THREAD

**Issue by fishcharlie** [reinterpretcat/lfs#18]
According to the following file it says `NOTE: skipped. Check 8.4 chapter of LFS book for details`.

https://github.com/reinterpretcat/lfs/blob/master/scripts/build/8.4-setup-grub.sh

Although the book says it's not required, it doesn't give much detail about why it should be skipped. Is there a reason it was skipped? It looks like there was intention to do it and all the code is there.

**Comment by Khobalt** [comment]
Coming from an amateur here but I believe it’s because this is targeting an iso build and it is assumed it will be the only image on the disk.

Grub is the boot loader, ie., the software that runs after the bios on the machine but before the operating system. Since this is an iso it’s used to make a live disk and you boot from the boot menu be in bios from an entirely different drive, thereby not necessitating a boot loader.
